version: '3'
services:
    php:
        # image: 'php:7.2-fpm'
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: php
        links:
            - mariadb
        volumes:
            - './app:/var/www/html'
        depends_on:
            - mariadb

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '8080:80'
            - '4433:443'
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'

    mariadb:
        image: mariadb:10.3.9
        container_name: mariadb
        restart: 'on-failure'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
        volumes:
            - ${PWD}

   
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - mariadb
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
            PMA_ARBITARY: 1
        restart: always
        ports:
            - "8081:80"
